audio_preprocessing:
  original_sample_rate: 44100
  new_sample_rate: 16000

model_trainer:
  epochs: 30
  batch_size: 32
  learning_rate: 0.0001
  n_cnn_layers: 3
  n_rnn_layers: 3
  rnn_dim: 256
  n_class: 29 # 28 characters + 1 for blank
  blank_index: 28
  n_feats: 128
  cnn_out_channels: 128
  stride: 2
  dropout: 0.1
