audio_preprocessing:
  original_sample_rate: 44100
  new_sample_rate: 16000

model_trainer:
  epochs: 32
  batch_size: 12
  learning_rate: 0.0001
  n_cnn_layers: 3
  n_rnn_layers: 2
  rnn_dim: 256
  n_class: 29
  blank_index: 28
  n_feats: 128
  cnn_out_channels: 128
  stride: 2
  dropout: 0.2

nlp_model_trainer:
  data_path: artifacts/data_ingestion/nlp_train_data.csv
  model_path: artifacts/model_trainer/sentiment_model.pth
  vocab_path: artifacts/model_trainer/sentiment_vocab.json
  max_len: 200
  embedding_dim: 128
  hidden_dim: 256
  output_dim: 3
  n_layers: 2
  drop_prob: 0.5
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  label_to_int:
    negative: 0
    neutral: 1
    positive: 2
  int_to_label:
    '0': 'negative'
    '1': 'neutral'
    '2': 'positive'